name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Export INE
        run: make export
